MVCAssignment/Models/FeverCheck.cs
///Models/FeverCheck.cs

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCAssignment.Models
{
    public class FeverCheck
    {
        public float MyTemp { get; set; }
        public string MyTempResult { get; set; }
        public bool SetBold { get; set; }
        public bool CelsiusOn { get; set; }

        //Calculates normal, fever or hypothermia status
        public static string TempCalc(FeverCheck Fever,float MyTemp)
        {
            bool hasFever = false;
            bool hasHypo = false;

            switch (Fever.CelsiusOn)
            {
                case true:
                    {
                        //When checkbox is set to celsius (checked), it uses these values
                        hasFever = (MyTemp > 37.7) ? true : false;
                        hasHypo = (MyTemp < 35) ? true : false;
                        break;
                    }
                case false:
                    {
                        //When checkbox is set to fahrenheit (unchecked), it uses these values
                        hasFever = (MyTemp > 99.86) ? true : false;
                        hasHypo = (MyTemp < 95) ? true : false;
                        break;
                    }
            }

            //Uses 0 value as indication nothing (worthwhile) has been put in
            if (MyTemp == 0)
            {
                Fever.MyTempResult = "Your result will show up here.";
            }
            //Temperature indicates fever
            else if (hasFever)
            {
                Fever.MyTempResult = "Whoa, you have a fever. Go to bed!";
                Fever.SetBold = true;
            }
            //Temperature indicates hypothermia
            else if (hasHypo)
            {
                Fever.MyTempResult = "You have hypothermia, not fever!";
                Fever.SetBold = true;
            }
            //Temperature is within normal range
            else
            {
                Fever.MyTempResult = "You're fine, stop being paranoid.";
            }

            return Fever.MyTempResult;
        }

        //Sets the display text for unit depending on user choice
        public string UnitChoice(bool CelsiusOn)
        {
            string unitText = "";
            unitText = (CelsiusOn == true) ? " Celsius" : " Fahrenheit";

            return unitText;
        }
    }
}

MVCAssignment/Models/GuessingGame.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MVCAssignment.Models;

namespace MVCAssignment.Models
{
    public class GuessingGame
    {
        //Declaring variables
        public List<string> guessRecord;
        public string Result { get; set; }
        public Random rand;
        public HttpCookie highscore;

        public int NumChoice { get; set; }
        public int NumRand { get; set; }
        public bool wonGame;

        //Initializing through constructor
        public GuessingGame()
        {
            Result = "Your result will show up here.";
            wonGame = false;
            NumChoice = 0;
            NumRand = 0;
            guessRecord = new List<string>();

            rand = new Random();
        }

        //Method to randomize input numbers
        public int NumRandomizer()
        {
            NumRand = rand.Next(1, 100);
            return NumRand;
        }

        //Evaluates guess and returns result
        public string ChoiceEvaluation(int SessionRand)
        {
            //If you win
            if (NumChoice == SessionRand)
            {
                Result = "You got it right! Guess again to continue playing.";
                wonGame = true;
            }
            //Guess too low
            else if (NumChoice < SessionRand)
            {
                Result = "Sorry, your number was too small!";
            }
            //Guess too high
            else if (NumChoice > SessionRand)
            {
                Result = "Shooting for the stars? Number was too big!";
            }

            return Result;
        }

        //Decides whether to add the guess to record or not
        public List<string> AddToRec(List<string> guessRecord)
        {
            //If choice is within margins, add it to record
            if (NumChoice >= 1 && NumChoice <= 100)
            {
                guessRecord.Add(NumChoice.ToString());
            }
            //Error if input is invalid
            else
            {
                Result = "Oops! Your guess must be between 1 and 100!";
            }

            return guessRecord;
        }

        //Selects highscore result
        public string SetHighscore(string prevScore)
        {
            int prevScoreInt = Convert.ToInt16(prevScore);
            string newScore = "0";

            //Sets highscore first time (previous is zero)
            if (prevScoreInt == 0)
            {
                newScore = guessRecord.Count.ToString();
            }
            //Sets new highscore if previous number is lower than the new
            else if (guessRecord.Count < prevScoreInt)
            {
                newScore = guessRecord.Count.ToString();
            }
            //Echoes the score back if highscore wasn't achieved
            else
            {
                newScore = prevScore;
            }

                return newScore;
        }
    }
}

MVCAssignment/Models/People.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace MVCAssignment.Models
{
    [Bind(Include = "AddName, AddPhone, AddCity")]
    public class People
    {

        #region DATABASE

        //Creates a static collection to refer to as the actual list of people
        public static List<List<string>> PeopleRefData { get; set; } = new List<List<string>>()
        {
            /* Initializes the default people
            NAME, PHONE NUMBER, CITY */
            new List<string> { "Emma Svenson", "202-555-0107", "San Francisco" },
            new List<string> { "Arnold Jonsson", "202-555-0162", "San Diego" },
            new List<string> { "Yumi Waterman", "202-555-0175", "Seattle" },
            new List<string> { "Bluma Finnin", "202-555-0147", "Nashville" },
            new List<string> { "Levon Ferro", "202-555-0190", "New York" }
        };

        //Copies the previous list content to a new "working"-list for displaying people
        public static List<List<string>> PeopleData { get; set; } = new List<List<string>>(PeopleRefData);

        //Creates new ViewDataDictionary for rowId
        public ViewDataDictionary customVDD = new ViewDataDictionary();

        #endregion DATABASE

        #region FORM PROPS

        public string SearchString { get; set; }

        [Required(ErrorMessage = "Name required")]
        public string AddName { get; set; }

        [Required(ErrorMessage = "Phone required")]
        public string AddPhone { get; set; }

        [Required(ErrorMessage = "City required")]
        public string AddCity { get; set; }

        public int RowNum { get; set; }

        #endregion FORM PROPS

        #region LOGIC METHODS

        /*Selects anything if SearchString is null, else finds a substring match and selects parent.
            Not perfect since it will select a list up to 3 times if there are 3 different matches in one list,
            but it will do for now.*/
        public void Search(People People, People people)
        {
            if (SearchString != null)
            {
                //Mines out the relevant sources within the master list
                var matchingvalues =
                from li in PeopleData
                from str in li

                    //where at least one substring in lowercase equals the lowercased SearchString
                where str.ToLowerInvariant().Contains(SearchString.ToLowerInvariant())
                //Selects the parent list of such a string
                select li;

                //Replaces main list-of-lists with the final filtered list-of-lists
                PeopleData = new List<List<string>>(matchingvalues);
            }
            else
            {
                //Find any sublists at all
                var matchingvalues =
                    from li in PeopleData
                    select li;

                //Replaces main list-of-lists with the final filtered list-of-lists
                PeopleData = new List<List<string>>(matchingvalues);
            }
        }

        //Function to call with session states to load them into the current states (if they're not null)
        public void LoadStates(List<List<string>> people, List<List<string>> reference, int? row)
        {
            if (people != null)
            {
                PeopleData = people;
            }

            if (reference != null)
            {
                PeopleRefData = reference;
            }

            if (row != null)
            {
                RowNum = (int)(row);
            }
        }

        //Method for building new person list and adding it
        public void Add(People people)
        {
            //Prepares a list
            List<string> newPerson = new List<string>();

            //Puts together data into the list
            newPerson.Add(people.AddName);
            newPerson.Add(people.AddPhone);
            newPerson.Add(people.AddCity);

            //Adds to list permanently
            PeopleRefData.Add(newPerson);
        }

        public void RemovePerson(int? removed)
        {
            if (removed != null)
            {
                //
                People.PeopleRefData.RemoveAt((int)(removed));
            }
        }

        //Saves form properties into the list
        public void SaveFormValues(int targetRow)
        {
            //Saving form property values into the list of the target row
            PeopleData[targetRow][0] = AddName;
            PeopleData[targetRow][1] = AddPhone;
            PeopleData[targetRow][2] = AddCity;

            //Copying change over into reference
            PeopleRefData[targetRow][0] = PeopleData[targetRow][0];
            PeopleRefData[targetRow][1] = PeopleData[targetRow][1];
            PeopleRefData[targetRow][2] = PeopleData[targetRow][2];
        }
    }

    #endregion LOGIC METHODS

}

MVCAssignment/Controllers/FeaturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCAssignment.Models;

namespace MVCAssignment.Controllers
{
    public class FeaturesController : Controller
    {
        //FEVER CHECK

        //GET: FeverCheck
        [Route("~/FeverCheck")]
        public ActionResult FeverCheck()
        {
            FeverCheck Fever = new Models.FeverCheck();
            Fever.MyTemp = 0.0F;
            Fever.MyTempResult = "Your result will show up here.";
            Fever.SetBold = false;
            Fever.CelsiusOn = true;

            return View(Fever);
        }

        //Action method exclusive to http posting, called by FeverCheck form
        [HttpPost]
        public ActionResult FeverCheck(FeverCheck Fever)
        {
            Fever.MyTempResult = Models.FeverCheck.TempCalc(Fever, Fever.MyTemp);
            return View(Fever);
        }


        // -------------------------------------------------------------------------------
        //GUESSING GAME

        //Game restarts when page is reloaded outside the form
        [HttpGet]
        public ActionResult GuessingGame()
        {
            //Page model
            GuessingGame Guess = new GuessingGame();

            //Initializes cookie used for highscore outside game session, set to last 1 day
            if (Request.Cookies["score"] != null)
            {
                Guess.highscore = new HttpCookie("score", "0");
                Guess.highscore.Expires = DateTime.Now.AddDays(1);
                Response.Cookies.Add(Guess.highscore);
            }

            //Gives NumRand a random number, will be hidden from user
            Guess.NumRand = Guess.NumRandomizer();

            //Initializing session variables
            Session["Random"] = Guess.NumRand;
            Session["Choice"] = 0;
            Session["Evaluation"] = Guess.Result;
            Session["GuessRecord"] = Guess.guessRecord;

            return View(Guess);
        }

        //This Action is called when number form is submitted (postback)
        [HttpPost]
        public ActionResult GuessingGame(GuessingGame Guess)
        {
            //Adds choice to its Session so user can keep their last guess in the box after guessing
            Session["Choice"] = Guess.NumChoice;

            //Updates random variable with stored value
            Guess.NumRand = (int)Session["Random"];

            //Updates record with its Session
            Guess.guessRecord = (List<string>)Session["GuessRecord"];

            //Calls on method to select result based on a comparison between the random and the guess
            Guess.Result = Guess.ChoiceEvaluation(Guess.NumRand);

            //If choice is valid, add to record and update record Session, otherwise give error message
            Guess.AddToRec((List<string>)Session["GuessRecord"]);

            //Result text to its session
            Session["Evaluation"] = Guess.Result;

            //IF WON
            if (Guess.wonGame)
            {
                //When record is lower than previously stored highscore, update highscore cookie
                Response.Cookies["score"].Value = Guess.SetHighscore(Request.Cookies["score"].Value);

                //Resets for next round
                Guess.guessRecord.Clear();
                Guess.NumChoice = 0;

                //Gives a new random number for next round
                Guess.NumRand = Guess.NumRandomizer();
            }
            Session["Random"] = Guess.NumRand;

            return View(Guess);
        }


        // -------------------------------------------------------------------------------

        People people = new People();

        //GET: People
        [HttpGet]
        public ActionResult People(People People, People people)
        {
            //Loads lists from session states only if the states have been created
            people.LoadStates((List<List<string>>)(Session["People"]),
                ((List<List<string>>)(Session["Reference"])),
                (int?)(Session["Row"]));

            //Resets list of people after a search to get the full list again
            People.PeopleData = People.PeopleRefData;

            //Saving lists into their sessions
            Session["Reference"] = People.PeopleRefData;
            Session["People"] = People.PeopleData;

            people.customVDD.Add(new KeyValuePair<string, object>("rowId", "0"));

            //Prevents errors from showing on initial load
            ModelState.Clear();

            return View(people);
        }

        //POST: People
        [HttpPost]
        public ActionResult People(People people)
        {
            //Re-checks model
            TryUpdateModel(people);

            return View(people);
        }

        //GET: _PartialItem
        [HttpGet]
        public PartialViewResult _PartialItem(People People, People people, object custVDD)
        {
            //Loads lists from session states only if the states have been created
            people.LoadStates((List<List<string>>)(Session["People"]),
                ((List<List<string>>)(Session["Reference"])),
                (int?)(Session["Row"]));

            //Narrows down PeopleList based on SearchString then updates inside method
            people.Search(People, people);

            //Stores row number from View
            people.customVDD = (ViewDataDictionary)(custVDD);

            //Saving lists into their sessions
            Session["Reference"] = People.PeopleRefData;
            Session["People"] = People.PeopleData;

            return PartialView(people);
        }

        //GET: _PartialEdit
        [HttpGet]
        public PartialViewResult _PartialEdit(People people)
        {
            //Prevents errors from showing on initial load
            ModelState.Clear();

            return PartialView(people);
        }

        //POST: _PartialEdit
        [HttpPost]
        //"People People" param added just to allow overload
        public PartialViewResult _PartialEdit(People People, People people)
        {
            //Re-checks model
            TryUpdateModel(people);

            //Checks form validity against model
            if (ModelState.IsValid)
            {
                //Returns Partial with updated values
                return PartialView("_PartialItem", people);
            }

            //Returns the same Partial if model isn't valid
            return PartialView(people);
        }
    }
}

MVCAssignment/Views/Features/FeverCheck.cshtml
@*/Views/Features/FeverCheck.cshtml*@

@model MVCAssignment.Models.FeverCheck

@{
    ViewBag.Title = "FeverCheck";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h1>Fever check</h1>

@* Creates form which posts by refreshing page *@
@using (Html.BeginForm("FeverCheck", "Features", FormMethod.Post))
{
    <fieldset>
        <legend>Your body temperature:</legend>
        <div>
            @* Html helper picks element for temperature value *@
            @Html.EditorFor(Model => Model.MyTemp) @Model.UnitChoice(Model.CelsiusOn)
        </div>
        <div>
            @* Submit button for the form *@
            <input type="submit" value="Submit" alt="submit" />
        </div>
        <br />
        <div>
            @* Result / placeholder is displayed *@
            <span id="boldResult">
                @Html.DisplayFor(m => m.MyTempResult)
            </span>
            @* When user has hypothermia or fever, the result message sets to bold *@
            @if (Model.SetBold == true)
            {
                <script>document.getElementById("boldResult").style.fontWeight = "bold"</script>
            }
        </div>
        <br />
        <div>
            @* A checkbox that initially sets itself to true *@
            Use Celsius: @Html.CheckBoxFor(m => m.CelsiusOn,
                        new { value = true })
        </div>
        <br />

    </fieldset>

    <br />
}

MVCAssignment/Views/Features/GuessingGame.cshtml
@*/Views/Features/GuessingGame.cshtml*@

@model MVCAssignment.Models.GuessingGame

@{
    ViewBag.Title = "GuessingGame";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>Welcome to the Guessing Game</h2>

@using (Html.BeginForm(controllerName: "Features", actionName: "GuessingGame", method: FormMethod.Post))
{
    <div>
        <p>Guess a number between 1-100!</p>
    </div>


    <div>
        @{
            //Update to fit Session
            Model.NumChoice = Convert.ToInt16(Session["Choice"]);
        }

        @* Textbox bound to NumChoice *@
        Choice: @Html.EditorFor(Model => Model.NumChoice)
    </div>

    <br />

    <div>
        @{
            //Changes result to previously stored Session result
            Model.Result = Session["Evaluation"].ToString();
        }

        Result: @Html.DisplayFor(Model => Model.Result)
    </div>

    <div>
        @{
            //Updates record with its Session
            Model.guessRecord = (List<string>)Session["GuessRecord"];
        }

        <br />

        <input type="submit" value="Guess" />

        <br />
        <br />

        Guesses(@Model.guessRecord.Count.ToString()):

        <br />

        @{
            for (int i = 0; i < Model.guessRecord.Count; i++)
            {
                @Model.guessRecord.ElementAt(i);
                <span>| </span>
            }
        }

    </div>

    <br />

    <div>
        @Html.ActionLink("New Game", "GuessingGame")
    </div>

    <br />

    <div>

        @* Displays highscore *@
        Highscore: @Request.Cookies["score"].Value
    </div>

            }

MVCAssignment/Views/Features/People.cshtml
@model MVCAssignment.Models.People

@{
    ViewBag.Title = "People";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>People</h2>

@*--SEARCH FORM---------------------------------------------------------------------------------*@

@* Uses AJAX HttpGet form to search / filter *@
@using (Ajax.BeginForm(ajaxOptions: new AjaxOptions
{
    //AJAX specifications
    HttpMethod = "GET",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "pList"
}, controllerName: "Features", actionName: "_PartialItem", routeValues: new { ajaxUpdate = true }))
{
    //Html content
    @Html.DisplayNameFor(m => m.SearchString)
    <br />
    @Html.EditorFor(m => m.SearchString)
    <input type="submit" value="search" />
}

<br />

@*--LIST OF PEOPLE---------------------------------------------------------------------------------*@

<div style="font-weight:bold; background-color:lightgrey; border-bottom:1px solid black">
    <span style="display:inline-block; width:250px"><span>Name</span></span>
    <span style="display:inline-block; width:250px">Phone number</span>
    <span style="display:inline-block; width:250px">City</span>
    <span style="display:inline-block">Edit</span>
</div>
<br />

@* For each property / row in PeopleData *@
@for (int r = 0; r < MVCAssignment.Models.People.PeopleData.Count; r++)
{

    @* Div for replacing with AJAX *@
    <div id="pList">
        @{ Model.customVDD["rowId"] = r.ToString(); }
        @Html.Partial(partialViewName: "_PartialItem", model: Model, viewData: Model.customVDD)
    </div>

}

@*--ADD FORM---------------------------------------------------------------------------------*@

@using (Html.BeginForm(controllerName: "Features", actionName: "People", method: FormMethod.Post))
{
    <label style="font-weight:bold">Add person:</label>

    <br />
    <br />

    @Html.DisplayNameFor(m => m.AddName)
    <br />
    @Html.EditorFor(m => m.AddName)
    @Html.ValidationMessageFor(m => m.AddName)
    <br />

    @Html.DisplayNameFor(m => m.AddPhone)
    <br />
    @Html.EditorFor(m => m.AddPhone)
    @Html.ValidationMessageFor(m => m.AddPhone)
    <br />

    @Html.DisplayNameFor(m => m.AddCity)
    <br />
    @Html.EditorFor(m => m.AddCity)
    @Html.ValidationMessageFor(m => m.AddCity)
    
    <br />
    <br />

    <input type="submit" />
}

@* AJAX HttpPost form to add people *@
@Ajax.BeginForm(ajaxOptions: new AjaxOptions
{
    //AJAX specifications
    HttpMethod = "POST",
    InsertionMode = InsertionMode.InsertAfter,
    UpdateTargetId = "pList"
}, controllerName: "Features", actionName: "_PartialItem")
{
@* Html content *@
@Html.DisplayNameFor(m => m.SearchString)
<br />
<input id="SearchString" name="SearchString" type="search" placeholder="filter">
<input type="submit" value="search" />
    }